%
% MATLAB commands (clearpath) generated by Rhapsody Control System Designer
% Model Name: JuanSampleModel
% Simulink Model Name: TheSystem_02
% Generated Date: Thu Nov 03 18:38:14 CET 2022
%
rmpath('C:\Users\20204920\OneDrive - TU Eindhoven\PDEng\Projects\Final_Project\TUeProject\Development\Parser\Rhapsody\Models\SimulinkModel')
