%
% MATLAB commands (model creation) generated by Rhapsody Control System Designer
% Model Name: JuanSampleModel
% Structured Simulink Model Name: TheSystem_02
% Generated Date: Thu Nov 03 18:34:21 CET 2022
%
try
	clear all
	delete mex.log
	if verLessThan('matlab', '8.6') 
		mexcmd = fileread('build_sfunction.m');
		ret = system([mexcmd ' > mex.log']);
		if (ret ~= 0)
			err = MException('Rhapsody:mex', 'Cannot build S-function');
			throw(err)
		end
	else
		fid = fopen('mex.log','w+');
		try
			build_sfunction
		catch e
			fprintf(fid, '%s', e.message);
			fclose(fid);
			err = MException('Rhapsody:mex', 'Cannot build S-function');
			throw(err)
		end
		fclose(fid);
	end
	bdclose('TheSystem_02_Rhap')
	TheSystem_02_setpath
	new_system('TheSystem_02_Rhap')
	set_param('TheSystem_02_Rhap', 'Description', sprintf(''))
	set_param('TheSystem_02_Rhap', 'StartTime', '0.0')
	set_param('TheSystem_02_Rhap', 'StopTime', '10.0')
	set_param('TheSystem_02_Rhap', 'InlineParams', 'on')
	set_param('TheSystem_02_Rhap', 'ParameterArgumentNames', '')
	add_block('built-in/ModelReference', 'TheSystem_02_Rhap/itsMonitor_02', 'ModelName', 'SineWaveDisplay', 'Position', [660 167 876 281], 'SimulationMode', 'Normal', 'Description', sprintf(''))
	add_block('built-in/S-Function', 'TheSystem_02_Rhap/rhap_s_function', 'FunctionName', 'RhapSFunc_SFunctionBlockTheSystem_02', 'Position', [111 145 321 259], 'Parameters', 'sampleTime', 'Mask', 'on', 'MaskPromptString','Sample time', 'MaskValueString', '0.01', 'MaskVariables', 'sampleTime=@1', 'MaskDescription','S-Function generated by Rhapsody', 'MaskDisplay', sprintf('port_label(''output'', 1, ''itsMonitor_02_sinIn'')\n'))
	rhap_oport = 'rhap_s_function/1';
	load_system('SineWaveDisplay')
	rhap_iport = ['itsMonitor_02', '/', get_param('SineWaveDisplay/sinIn', 'Port')];
	rhap_new_line = add_line('TheSystem_02_Rhap', rhap_oport, rhap_iport, 'autorouting', 'on');
	set_param(rhap_new_line, 'Name', 'itsMonitor_02_sinIn')
	clear rhap_oport rhap_iport rhap_new_line
	open_system('TheSystem_02_Rhap')
	save_system('TheSystem_02_Rhap')
	mkdir('success')
catch ME
	msgbox(ME.message, 'Rhapsody - Error', 'error', 'replace')
	mkdir('failure')
end
