%
% MATLAB commands (setpath) generated by Rhapsody Control System Designer
% Model Name: JuanSampleModel
% Simulink Model Name: TheSystem
% Generated Date: Wed Nov 02 09:35:01 CET 2022
%
addpath('C:\Users\20204920\OneDrive - TU Eindhoven\PDEng\Projects\Final_Project\TUeProject\Development\Parser\Rhapsody\Models\JuanSampleModel\Simulink', ...
'C:\Users\20204920\OneDrive - TU Eindhoven\PDEng\Projects\Final_Project\TUeProject\Development\Parser\Rhapsody\Models\SimulinkModel')
rmpath('C:\Users\20204920\OneDrive - TU Eindhoven\PDEng\Projects\Final_Project\TUeProject\Development\Parser\Rhapsody\Models\JuanSampleModel\SimulinkAnim')
