%
% MATLAB commands (sim) generated by Rhapsody Control System Designer
% Model Name: JuanSampleModel
% Simulink Model Name: TheSystem
% Generated Date: Mon Oct 31 15:30:53 CET 2022
%
try
	sim('TheSystem_Rhap')
catch ME
	msgbox(ME.message, 'Rhapsody - Error', 'error', 'replace')
end
