%
% MATLAB commands (model creation) generated by Rhapsody Control System Designer
% Model Name: JuanSampleModel
% Structured Simulink Model Name: TheSystem
% Generated Date: Wed Nov 02 09:35:01 CET 2022
%
try
	clear all
	bdclose('TheSystem_Rhap')
	TheSystem_setpath
	new_system('TheSystem_Rhap')
	set_param('TheSystem_Rhap', 'Description', sprintf(''))
	set_param('TheSystem_Rhap', 'StartTime', '0.0')
	set_param('TheSystem_Rhap', 'StopTime', '10.0')
	set_param('TheSystem_Rhap', 'InlineParams', 'on')
	set_param('TheSystem_Rhap', 'ParameterArgumentNames', '')
	add_block('built-in/ModelReference', 'TheSystem_Rhap/itsDriver', 'ModelName', 'SineWaveGenerator', 'Position', [82 169 227 283], 'SimulationMode', 'Normal', 'Description', sprintf(''))
	add_block('built-in/ModelReference', 'TheSystem_Rhap/itsMonitor', 'ModelName', 'SineWaveDisplay', 'Position', [383 220 547 334], 'SimulationMode', 'Normal', 'Description', sprintf(''))
	load_system('SineWaveGenerator')
	rhap_oport = ['itsDriver', '/', get_param('SineWaveGenerator/sinOut', 'Port')];
	load_system('SineWaveDisplay')
	rhap_iport = ['itsMonitor', '/', get_param('SineWaveDisplay/sinIn', 'Port')];
	rhap_new_line = add_line('TheSystem_Rhap', rhap_oport, rhap_iport, 'autorouting', 'on');
	set_param(rhap_new_line, 'Name', 'itsDriver_sinOut')
	clear rhap_oport rhap_iport rhap_new_line
	open_system('TheSystem_Rhap')
	save_system('TheSystem_Rhap')
	mkdir('success')
catch ME
	msgbox(ME.message, 'Rhapsody - Error', 'error', 'replace')
	mkdir('failure')
end
