try
	display('Compiling S-Function')
	build_sfunction
	display('S-Function Compilation Done')
	display('Generating Simulink Model')
	
	new_system('RhapSFunc_SFunctionBlockTheSystem_02_Model')
	set_param('RhapSFunc_SFunctionBlockTheSystem_02_Model', 'StartTime', '0.0')
	set_param('RhapSFunc_SFunctionBlockTheSystem_02_Model', 'StopTime', '100.0')
	set_param('RhapSFunc_SFunctionBlockTheSystem_02_Model', 'InlineParams', 'on')
	set_param('RhapSFunc_SFunctionBlockTheSystem_02_Model', 'PreLoadFcn', '');
	add_block('built-in/S-Function', 'RhapSFunc_SFunctionBlockTheSystem_02_Model/RhapSFunc_SFunctionBlockTheSystem_02', 'FunctionName', 'RhapSFunc_SFunctionBlockTheSystem_02', 'Position', [205, 85, 390, 195], 'Parameters', 'sampleTime', 'Mask', 'on', 'MaskPromptString','Sample time', 'MaskValueString', '0.01', 'MaskVariables', 'sampleTime=@1', 'MaskDescription','S-Function generated by Rhapsody')
	set_param('RhapSFunc_SFunctionBlockTheSystem_02_Model/RhapSFunc_SFunctionBlockTheSystem_02', 'MaskDisplay', sprintf('port_label(''output'',1,''itsMonitor_02_sinIn'')'))
	save_system('RhapSFunc_SFunctionBlockTheSystem_02_Model')
	open_system('RhapSFunc_SFunctionBlockTheSystem_02_Model')
	display('Simulink Model Generation Done')
catch ME
	display('Error!')
	display(['    ', ME.message])
end
