%
% MATLAB commands (sim) generated by Rhapsody Control System Designer
% Model Name: JuanSampleModel
% Simulink Model Name: TheSystem_02
% Generated Date: Thu Nov 03 18:38:14 CET 2022
%
try
	sim('TheSystem_02_Rhap')
catch ME
	msgbox(ME.message, 'Rhapsody - Error', 'error', 'replace')
end
